<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Product;
use App\Models\Review;

class CurtainProductCrawlerSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Đảm bảo có đầy đủ các danh mục rèm thịnh hành
        $newCategories = [
            [
                'name' => 'Rèm Tổ Ong Cách Nhiệt',
                'slug' => 'rem-to-ong-cach-nhiet',
                'description' => 'Rèm tổ ong đệm khí cản nhiệt, ngăn lạnh điều hòa và làm vách ngăn xếp gọn thông minh.',
                'image' => 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Rèm Roman Xếp Lớp',
                'slug' => 'rem-roman-xep-lop',
                'description' => 'Rèm roman xếp nếp tầng thanh lịch, tối ưu diện tích cho cửa sổ phòng ngủ và căn hộ hiện đại.',
                'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
        ];

        foreach ($newCategories as $cat) {
            Category::firstOrCreate(['slug' => $cat['slug']], $cat);
        }

        $allCategories = Category::all()->keyBy('slug');

        // 2. Danh sách 14 mẫu rèm mới cào chi tiết với thông số thực tế
        $crawledProducts = [
            // Rèm Vải
            [
                'category_id' => $allCategories['rem-vai-2-lop']->id ?? 1,
                'name' => 'Rèm Vải Linen Bỉ Thô Mộc Wabi Sabi',
                'slug' => 'rem-vai-linen-bi-tho-moc-wabi-sabi',
                'sku' => 'REM-LN-08',
                'price' => 1150000,
                'sale_price' => 950000,
                'price_unit' => 'meter',
                'min_area' => 1.00,
                'min_width' => 100,
                'max_width' => 600,
                'min_height' => 100,
                'max_height' => 450,
                'blackout_rate' => 90,
                'installation_type' => 'indoor',
                'stock' => 40,
                'material' => '100% Sợi Lanh Linen Tự Nhiên Bỉ',
                'origin' => 'Bỉ (Belgium)',
                'description' => 'Vải sợi lanh Linen nguyên bản, thoáng khí, không tích điện, tôn vinh vẻ đẹp tự nhiên mộc mạc và tĩnh tại cho gia chủ yêu thích phong cách Japandi và Wabi Sabi.',
                'image' => 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-vai-2-lop']->id ?? 1,
                'name' => 'Rèm Vải Kháng Khuẩn Nhật Bản Sangetsu',
                'slug' => 'rem-vai-khang-khuan-nhat-ban-sangetsu',
                'sku' => 'REM-SG-09',
                'price' => 1680000,
                'sale_price' => 1450000,
                'price_unit' => 'meter',
                'min_area' => 1.00,
                'min_width' => 100,
                'max_width' => 550,
                'min_height' => 100,
                'max_height' => 400,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 25,
                'material' => 'Vải Sợi Nano Sangetsu Kháng Khuẩn',
                'origin' => 'Nhật Bản (Japan)',
                'description' => 'Dòng rèm cao cấp đạt chứng nhận JIS Nhật Bản về khả năng kháng khuẩn, ngăn nấm mốc và chống bám bụi mịn PM2.5. An toàn tuyệt đối cho gia đình có trẻ nhỏ.',
                'image' => 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-vai-2-lop']->id ?? 1,
                'name' => 'Rèm Vải Voan Thêu Họa Tiết Sen Vàng Thủ Công',
                'slug' => 'rem-vai-voan-theu-hoa-tiet-sen-vang-thu-cong',
                'sku' => 'REM-VN-10',
                'price' => 750000,
                'sale_price' => 680000,
                'price_unit' => 'meter',
                'min_area' => 1.00,
                'min_width' => 80,
                'max_width' => 600,
                'min_height' => 100,
                'max_height' => 450,
                'blackout_rate' => 40,
                'installation_type' => 'indoor',
                'stock' => 50,
                'material' => 'Voan Lụa Mềm Thêu Chỉ Vàng',
                'origin' => 'Việt Nam xuất khẩu',
                'description' => 'Lớp voan lụa xuyên sáng mềm mại điểm xuyết hoa sen thêu tay thủ công tinh xảo, tạo chiều sâu mềm mại và sang trọng khi đón ánh nắng sớm mai.',
                'image' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Rèm Cầu Vồng
            [
                'category_id' => $allCategories['rem-cau-vong-han-quoc']->id ?? 2,
                'name' => 'Rèm Cầu Vồng Modero Crystal Blackout 100%',
                'slug' => 'rem-cau-vong-modero-crystal-blackout',
                'sku' => 'REM-CV-11',
                'price' => 1050000,
                'sale_price' => 890000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 40,
                'max_width' => 280,
                'min_height' => 50,
                'max_height' => 320,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 35,
                'material' => '100% Polyester Dệt 3 Lớp Cản Sáng',
                'origin' => 'Modero Hàn Quốc',
                'description' => 'Dòng sản phẩm cản sáng 100% cao cấp nhất từ Modero Korea, thiết kế vân dệt nổi 3D sang trọng, chống bạc màu dưới ánh nắng gắt hướng Tây.',
                'image' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-cau-vong-han-quoc']->id ?? 2,
                'name' => 'Rèm Cầu Vồng Eco Blinds Chống Bám Bụi & Kháng Cháy',
                'slug' => 'rem-cau-vong-eco-blinds-chong-bam-bui',
                'sku' => 'REM-CV-12',
                'price' => 780000,
                'sale_price' => 690000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 40,
                'max_width' => 260,
                'min_height' => 50,
                'max_height' => 300,
                'blackout_rate' => 90,
                'installation_type' => 'indoor',
                'stock' => 45,
                'material' => 'Vải Sợi Tổng Hợp Chống Tĩnh Điện',
                'origin' => 'Hàn Quốc',
                'description' => 'Phủ lớp Nano chống tĩnh điện ngăn bụi bẩn bám dính, đạt chứng chỉ kháng cháy lan tiêu chuẩn quốc tế, phụ kiện nhôm nguyên khối sơn tĩnh điện bóng mịn.',
                'image' => 'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Rèm Gỗ
            [
                'category_id' => $allCategories['rem-sao-go-tu-nhien']->id ?? 4,
                'name' => 'Rèm Gỗ Bách Hương Đỏ (Basswood) Bản 5cm Sang Trọng',
                'slug' => 'rem-go-bach-huong-do-basswood',
                'sku' => 'REM-SG-13',
                'price' => 1180000,
                'sale_price' => 990000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 50,
                'max_width' => 240,
                'min_height' => 60,
                'max_height' => 320,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 20,
                'material' => 'Gỗ Bách Hương Bắc Mỹ 100%',
                'origin' => 'Bắc Mỹ / Lắp ráp Việt Nam',
                'description' => 'Bản lá 50mm vân gỗ tự nhiên sắc sảo, mùi thơm gỗ nhẹ thư giãn, cách nhiệt tốt cho phòng làm việc giám đốc và phòng khách sang trọng.',
                'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-sao-go-tu-nhien']->id ?? 4,
                'name' => 'Rèm Sáo Gỗ Thông Tuyết Trắng Phong Cách Scandinavian',
                'slug' => 'rem-sao-go-thong-tuyet-trang-scandinavian',
                'sku' => 'REM-SG-14',
                'price' => 890000,
                'sale_price' => 790000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 45,
                'max_width' => 220,
                'min_height' => 50,
                'max_height' => 280,
                'blackout_rate' => 95,
                'installation_type' => 'indoor',
                'stock' => 30,
                'material' => 'Gỗ Thông Tuyết Nga Sơn UV Trắng',
                'origin' => 'Nga / Việt Nam',
                'description' => 'Tông màu trắng tuyết thanh lịch phối dây đai dệt vải canvas phong cách Bắc Âu tối giản, chống ẩm mốc tốt trong khí hậu nồm ẩm nhiệt đới.',
                'image' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Rèm Cuốn & Văn Phòng
            [
                'category_id' => $allCategories['rem-cuon-van-phong']->id ?? 3,
                'name' => 'Rèm Cuốn Lưới Sunscreen Lỗ Kim 3% Chống Lóa',
                'slug' => 'rem-cuon-luoi-sunscreen-lo-kim-chong-loa',
                'sku' => 'REM-RC-15',
                'price' => 420000,
                'sale_price' => 360000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 40,
                'max_width' => 300,
                'min_height' => 50,
                'max_height' => 350,
                'blackout_rate' => 70,
                'installation_type' => 'indoor',
                'stock' => 80,
                'material' => 'Sợi Thủy Tinh (Fiberglass) Phủ PVC',
                'origin' => 'Úc / Lắp ráp Việt Nam',
                'description' => 'Rèm cuốn lưới cản 97% tia cực tím nhưng vẫn giữ tầm nhìn bao quát ra khung cảnh thành phố bên ngoài. Rất thích hợp cho quán cafe, ban công căn hộ và phòng họp.',
                'image' => 'https://images.unsplash.com/photo-1540518614846-7ede433c5172?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-cuon-van-phong']->id ?? 3,
                'name' => 'Rèm Lá Dọc Văn Phòng Bản 10cm Chống Nắng Cản Nhiệt',
                'slug' => 'rem-la-doc-van-phong-ban-10cm-can-nhiet',
                'sku' => 'REM-LD-16',
                'price' => 260000,
                'sale_price' => 220000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 50,
                'max_width' => 400,
                'min_height' => 80,
                'max_height' => 400,
                'blackout_rate' => 90,
                'installation_type' => 'indoor',
                'stock' => 150,
                'material' => 'Vải Phủ Nhựa Polyester Chống Nước',
                'origin' => 'Đài Loan',
                'description' => 'Lá rèm xoay lật 180 độ điều chỉnh luồng sáng linh hoạt, thanh ray nhôm chịu lực kéo nhẹ êm, độ bền công trình trên 8 năm với chi phí tiết kiệm.',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
                'is_featured' => false,
                'is_active' => true,
            ],

            // Rèm Tự Động
            [
                'category_id' => $allCategories['rem-tu-dong-thong-minh']->id ?? 5,
                'name' => 'Bộ Rèm Động Cơ Tự Động Somfy Pháp Êm Ái Dưới 25dB',
                'slug' => 'bo-rem-dong-co-tu-dong-somfy-phap',
                'sku' => 'REM-TD-17',
                'price' => 6800000,
                'sale_price' => 5950000,
                'price_unit' => 'piece',
                'min_area' => 1.00,
                'min_width' => 120,
                'max_width' => 1000,
                'min_height' => 100,
                'max_height' => 600,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 12,
                'material' => 'Động Cơ Somfy Glydea Ultra 60e WT',
                'origin' => 'Pháp (France)',
                'description' => 'Thương hiệu động cơ rèm số 1 thế giới đến từ Pháp. Vận hành êm như tiếng lá rơi, bảo hành chính hãng 5 năm, tích hợp hệ thống nhà thông minh cao cấp.',
                'image' => 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-tu-dong-thong-minh']->id ?? 5,
                'name' => 'Rèm Trần Tự Động Giếng Trời Chống Nắng Biệt Thự',
                'slug' => 'rem-tran-tu-dong-gieng-troi-chong-nang',
                'sku' => 'REM-TD-18',
                'price' => 1850000,
                'sale_price' => 1620000,
                'price_unit' => 'sqm',
                'min_area' => 2.00,
                'min_width' => 100,
                'max_width' => 500,
                'min_height' => 100,
                'max_height' => 800,
                'blackout_rate' => 98,
                'installation_type' => 'indoor',
                'stock' => 15,
                'material' => 'Bạt Phủ Bạc Kháng Nắng & Motor Kép',
                'origin' => 'Hàn Quốc / Việt Nam',
                'description' => 'Hệ rèm trần kéo phẳng tự động che nắng giếng trời, mái kính tum biệt thự. Cảm biến mưa và nắng tự động đóng lại khi trời mưa hoặc nắng gắt.',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Rèm Tổ Ong
            [
                'category_id' => $allCategories['rem-to-ong-cach-nhiet']->id ?? 1,
                'name' => 'Rèm Tổ Ong Ngăn Lạnh Điều Hòa & Cách Nhiệt Hệ Kéo Tay',
                'slug' => 'rem-to-ong-ngan-lanh-dieu-hoa-cach-nhiet',
                'sku' => 'REM-TO-19',
                'price' => 750000,
                'sale_price' => 680000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 40,
                'max_width' => 260,
                'min_height' => 50,
                'max_height' => 300,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 50,
                'material' => 'Vải Không Dệt Tráng Bạc Lớp Đệm Khí',
                'origin' => 'Hàn Quốc',
                'description' => 'Cấu trúc lục giác tổ ong giữ lớp không khí tĩnh cách nhiệt và cản lạnh điều hòa thoát ra ngoài hiệu quả đến 95%. Xếp gọn chỉ còn 5cm khi thu lại.',
                'image' => 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => $allCategories['rem-to-ong-cach-nhiet']->id ?? 1,
                'name' => 'Vách Ngăn Tổ Ong Hệ Xếp Xích Không Ray Dưới',
                'slug' => 'vach-ngan-to-ong-he-xep-xich-khong-ray',
                'sku' => 'REM-TO-20',
                'price' => 1450000,
                'sale_price' => 1280000,
                'price_unit' => 'sqm',
                'min_area' => 1.50,
                'min_width' => 60,
                'max_width' => 600,
                'min_height' => 150,
                'max_height' => 320,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 30,
                'material' => 'Khung Nhôm Hệ 32 Sơn Tĩnh Điện & Vải Tổ Ong',
                'origin' => 'Nhập Khẩu Đồng Bộ',
                'description' => 'Giải pháp ngăn chia phòng khách và bếp, ngăn phòng điều hòa không cần xây tường. Đáy không ray giúp người già và trẻ nhỏ đi lại không bị vấp ngã.',
                'image' => 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],

            // Rèm Roman
            [
                'category_id' => $allCategories['rem-roman-xep-lop']->id ?? 1,
                'name' => 'Rèm Roman Kẹp Quạt Tân Cổ Điển Nhập Khẩu Bỉ',
                'slug' => 'rem-roman-kep-quat-tan-co-dien-bi',
                'sku' => 'REM-RM-21',
                'price' => 850000,
                'sale_price' => 720000,
                'price_unit' => 'sqm',
                'min_area' => 1.00,
                'min_width' => 40,
                'max_width' => 240,
                'min_height' => 50,
                'max_height' => 280,
                'blackout_rate' => 100,
                'installation_type' => 'indoor',
                'stock' => 35,
                'material' => 'Vải Gấm Bỉ Dệt Nổi Kháng Bụi',
                'origin' => 'Bỉ (Belgium)',
                'description' => 'Thiết kế may xếp lớp uốn lượn hình cánh quạt duyên dáng, thích hợp cho phòng ngủ Master, cửa sổ góc vòm biệt thự hoặc khách sạn boutique sang trọng.',
                'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($crawledProducts as $data) {
            $product = Product::updateOrCreate(['slug' => $data['slug']], $data);

            // Tạo các review mẫu chất lượng cao cho từng sản phẩm mới
            $sampleReviews = [
                [
                    'customer_name' => 'Anh Hải Đăng (Biệt thự Splendora)',
                    'customer_phone' => '0912***888',
                    'rating' => 5,
                    'comment' => 'Chất liệu mẫu ' . $product->name . ' này rất sắc nét, thợ đến lắp đặt cẩn thận và đúng giờ. Rất hài lòng về độ cách nhiệt và cản sáng.',
                    'status' => 'approved',
                ],
                [
                    'customer_name' => 'Chị Phương Anh (Chung cư Ngoại Giao Đoàn)',
                    'customer_phone' => '0988***234',
                    'rating' => 5,
                    'comment' => 'Lên rèm nhìn căn phòng ấm cúng và sang trọng hơn hẳn. Đường may phẳng phiu, các múi rèm rơi đều tăm tắp!',
                    'status' => 'approved',
                ],
                [
                    'customer_name' => 'Bác Trần Trọng Nghĩa (Phố cổ Hoàn Kiếm)',
                    'customer_phone' => '0903***567',
                    'rating' => 4,
                    'comment' => 'Màu sắc y hệt cây mẫu vải được nhân viên mang qua đo tại nhà. Rèm kéo êm tay, khung phụ kiện cứng cáp chắc chắn.',
                    'status' => 'approved',
                ],
            ];

            foreach ($sampleReviews as $rev) {
                Review::firstOrCreate([
                    'product_id' => $product->id,
                    'customer_name' => $rev['customer_name'],
                ], array_merge($rev, ['product_id' => $product->id]));
            }
        }
    }
}
